server:
  port: 8000

spring:
  application:
    name: apiGatewayService
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: http://127.0.0.1:8001/
          predicates:
            - Path=/first-service/**
        - id: second-service
          uri: http://127.0.0.1:8002/
          predicates:
            - Path=/second-service/**

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka